#!/usr/bin/env ruby
require "a_lox"
require "readline"
require "a_lox/commands/execute_source"

begin
  executable = ALox::ExecutableContainer.new
  vm = ALox::VM.new(error_reporter: nil) # TODO: error_reporter

  buffer = ""

  Readline.pre_input_hook = lambda do
    Readline.insert_text("  " * [buffer.count("{") - buffer.count("}"), 0].max)
    Readline.redisplay
  end

  while (line = Readline.readline(buffer.empty? ? "> " : "| ", true)&.chomp)
    if line.empty?
      ALox::Commands::ExecuteSource.call(buffer, executable: executable, vm: vm)
      buffer = ""
    else
      buffer += line
    end
  end

  puts "👋"
rescue Interrupt
  puts
  retry
end
