alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: lox-analyzer.svetlins.net
    type: PRIMARY
name: lox
region: fra
services:
  - environment_slug: ruby
    github:
      branch: master
      repo: svetlins/crafting-interpreters
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: lox-server
    routes:
      - path: /api
    run_command: ruby web.rb
    source_dir: /s1-web/web
static_sites:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: master
      repo: svetlins/crafting-interpreters
    name: frontend
    routes:
      - path: /
    source_dir: /s1-web/client
