alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: lox-analyzer.svetlins.net
    type: PRIMARY
name: lox
region: fra
static_sites:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: master
      repo: svetlins/crafting-interpreters
    name: frontend
    routes:
      - path: /
    source_dir: /s1-web/client
